-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'GUARDIAN_INVITE_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'GUARDIAN_INVITE_CANCELLED';
ALTER TYPE "AuditEventType" ADD VALUE 'GUARDIAN_LINK_REMOVED';
